name: Tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r test-requirements.txt

    - name: (Debug environment)
      run: |
        printenv
        python -V
        pip freeze

    - name: Check formatting, typing etc.
      run: |
        ruff format --diff
        ruff check
        mypy --strict dfrgblcdpy 

    - name: Build package
      run: |
        pip install setuptools
        python setup.py build sdist
